version: '2'
services:
  mysql:
    image: daocloud.io/library/mysql:5.7.16
    container_name: mysql
    volumes:
      - "./data:/var/lib/mysql"
      - "./mysqlconf:/ect/mysql"
    restart: always
    environment:
      TERM: xterm
      MYSQL_ROOT_PASSWORD: 102323
    expose:
     - "3306"
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress
  php:
#    build: ./php
    image: daocloud.io/qxhy123/docker-php:latest
    container_name: php
    volumes:
      - "./site:/var/www/html"
    restart: always
    links:
     - mysql:db
     - es
     - es_slave
    ports:
     - "9000"
     - "9001"
     - "9002"
    environment:
      TERM: xterm

  nginx:
    image: daocloud.io/library/nginx:1.11
    container_name: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./conf.d:/etc/nginx/conf.d"
      - "./site:/var/www/html"
    ports:
      - "80:80"
      - "9000:9000"
      - "9001:9001"
    links:
      - mysql:db
      - php
    restart: always
    environment:
      TERM: xterm
  es:
    image: elasticsearch:2.3
    container_name: es
    command:
      'elasticsearch -Des.cluster.name=es -Des.node.master=true -Des.node.name=node-1'
    volumes:
      - "./esconfig:/usr/share/elasticsearch/config"
      - "./esdata:/usr/share/elasticsearch/data"
    restart: always
    ports:
     - "9200:9200"
     - "9300:9300"
    environment:
      TERM: xterm
  es_slave:
    image: elasticsearch:2.3
    container_name: es_slave
    command:
      'elasticsearch -Des.cluster.name=es -Des.node.name=node-2 -Des.discovery.zen.ping.unicast.hosts=es'
    volumes:
      - "./es1config:/usr/share/elasticsearch/esslaveconfig"
      - "./es1data:/usr/share/elasticsearch/esslavedata"
    restart: always
    links:
      - es
    ports:
     - "9201:9200"
     - "9301:9300"
    environment:
      TERM: xterm
